### ISSUE TITLE
Created Date and Completed date for each checklist item in Excel Export

### ISSUE THREAD

**Issue by kngautham** [trapias/TrelloExport#40]
Your Extension is Amazing and I use it regularly for backing up my Boards to both Excel and HTML.

I have a suggestion that you can think of implementing in the future.

When I export Trello Board to Excel, There is already an option for one row per Checklist Item. 

Please for each Checklist item, allow us to export the created date and completed date for that individual Checklist item. 

Right now, you can export the main card created date and last activity date for each Row. 

Thank you very much for the extension. I have tried many extensions for exporting trello data, nothing comes close to yours in terms of functionality and versatility. Stay in touch and a big Thank you.

**Comment by trapias** [comment]
@kngautham I’m afraid there’s not a field in Trello API for the date when the card is marked completed - we have the dueComplete only.

https://developers.trello.com/docs/

**Comment by kngautham** [comment]
Hi,

Thanks again for your time. Already when using your extension and I export
to html, for every checklist item that has been completed, export tells the
completed date and person completing it for each checklist item. So I
thought same information can be exported for excel as well.

I understand API does not allow for exporting created date for each
checklist item,

Thanks again for replying.

**Comment by kngautham** [comment]
Thank you for your prompt reply. I have emailed Trello asking them to include the Checklist Item Created date to their API.

**Comment by kngautham** [comment]
Hi,

I spoke with Trello support and they said that all actions can be logged
and returned by webhooks. I am not a programmer and don't know anything
about webhooks.

Do let me know if this would help you with getting the created date for
checklist items.

Thank you very much for the extension

Gautham
---------- Forwarded message ---------
From: Trello Support <support@trello.com>
Date: Mon, May 14, 2018, 22:45
Subject: Re: API Access for history of the creation, modification, and
deletion of individual checklist items
To: Gautham Kn <kngautham@mitraventures.in>


Hey Gautham,

There are a number of actions that we don't return via the API. We keep
track of the action types that we do and don't return at:
https://developers.trello.com/reference/#action-types.

For the actions that we don't return via the API, the only way to access
them is via webhooks (https://developers.trello.com/webhooks). We will send
all actions to webhooks.

All the best,

Bentley
The Trello Team

Need priority support for your business? Check out Trello Business Class
<https://trello.com/business-class?utm_source=support-email&utm_medium=email&utm_term=footer&utm_campaign=support-business-class>
.
Visit our Trello community <https://community.atlassian.com/trello> to ask
other Trello users for how-to's or advice.

How satisfied were you with your interaction with Trello Support?
Very Satisfied
<https://secure.helpscout.net/satisfaction/152674419/record/1587544382/1/>
Neutral
<https://secure.helpscout.net/satisfaction/152674419/record/1587544382/2/>
  Not satisfied
<https://secure.helpscout.net/satisfaction/152674419/record/1587544382/3/>
{#HS:579523186-343871#}

**Comment by trapias** [comment]
@kngautham Webhooks basically require an HTTP(s) server to listen to messages sent from Trello: once you have such a server and configure Trello to call it, you can receive any update - also for actions not covered by the API - whenever you update your Trello boards.

The problem is we cannot have a webhook inside TrelloExport - we need an external server to store messages; and then we need that server to allow us to navigate the collected data, which could come "independently" by the way of HTML page(s), or integrated in TrelloExport by calling some API endpoint on the server itself.

I'm planning to improve TrelloExport with the help of external services like this, but cannot give a timing yet: this is still a side-project to me, my job and my children have the priority :-D

If you or anybody else's interested, such development could be accelerated by a donation - like the one that allowed us to get Twig templates for HTML export recently (see [this blog post](http://trapias.github.io/blog/2018/04/27/TrelloExport-1.9.43)).

Thank you for your help!

Alberto.
