### ISSUE TITLE
Filter through Trello labels

### ISSUE THREAD

**Issue by matts-newmorn** [trapias/TrelloExport#45]
This function appears to not be working currently, or is working in some way unknown at this time.
Applying a filter by label currently has no noticeable effect on export.

**Comment by matts-newmorn** [comment]
I still am not able to filter by label. I tried isolating the variables by turning off all other Chrome extensions to make sure nothing was interfering. Filter by List and Card are working as expected, but Filter by Label has no effect.

Running Chrome version 66.0.3359.139 on Windows

**Comment by trapias** [comment]
Will check asap

**Comment by trapias** [comment]
@matts-newmorn I made a new test and filter on labels is working as expected. Please consider all filters, since 1.9.40, do not act on string prefix but as a "like"; that is filters are no more of kind "string starts with [value]" but are "string CONTAINS [value]".

If you for example go to https://trello.com/b/MBnwUMwM/trelloexport and export filtering by label, writing "enhancement" as the filter string, you will see only a few cards exported - those having that label. The same for the "under review" label, which you can filter for example with "review".

**Comment by matts-newmorn** [comment]
I think I found the issue I was having - I did not know that filtering would only work if Current Board is selected. I had been trying to filter labels for "Select lists in Current Board" and when that is chosen, it seems to ignore the label filtering entirely.

I'm seeing that filtering will in fact work if you're exporting from the entire Current Board.

**Comment by trapias** [comment]
@matts-newmorn I’m looking into this, cannot remember if this was the expected behavior 😊

**Comment by matts-newmorn** [comment]
@trapias This is working great now. I greatly appreciate your continued effort on it. Thanks again.

**Comment by trapias** [comment]
👍
