### ISSUE TITLE
Error - Rate limit exceeded

### ISSUE THREAD

**Issue by htripi** [trapias/TrelloExport#85]
Hi Alberto
I am receiving an error in the export. Could you help me?
Thanks
![image](https://user-images.githubusercontent.com/62359404/123855058-d3fb9700-d8f5-11eb-8da7-0a1e0af95abf.png)

**Comment by trapias** [comment]
@htripi this is due to Trello rate limits, see https://help.trello.com/article/838-api-rate-limits#:~:text=To%20help%20prevent%20strain%20on,will%20return%20a%20429%20error.
This normally happens if you're exporting a ton of data: I'd suggest to export smaller amounts of data, the only solution I can think of is adding some delay between requests, but of course this would increase export times.

**Comment by trapias** [comment]
If anybody gets this error please share a board with me, so that I can replicate the problem and try to solve

**Comment by trapias** [comment]
Problem tracked in #81
